Bug/fix cherry pick missing commit
didymo/OnkoDICOM pull request #144
Opened 2021-08-02 10:07 UTC by eddieGong2604

This PR cherry pick missing commit that fixes crash in clinical data tab

(cherry picked from commit 9e25abd5f5af9583f7bbc70b809dbd067e5cdf67)

2021-08-02 10:11 UTC, tdlinh2712 requested changes

2021-08-02 10:11 UTC, tdlinh2712 commented on src/Controller/MainPageController.py
> +                # the sensitive data for this patient is missing so no editing can be performed
Please keep the edit from current files, and only change `button0=QtWidgets.QMessageBox.Ok` to `QtWidgets.QMessageBox.Ok`. The current texts comply with PEP 8 standard, only missing the typo `button0` fix.

2021-08-02 10:11 UTC, tdlinh2712 commented on src/Controller/MainPageController.py
> -            button_reply = QtWidgets.QMessageBox.warning(
same here.

2021-08-02 10:24 UTC, tdlinh2712 approved these changes

2021-08-05 03:18 UTC, DuyTungHa approved these changes

2021-08-05 03:42 UTC, LWMcClymont approved these changes

2021-08-05 11:43 UTC, JThomas2020 approved these changes
Team 19

2021-08-05 22:34 UTC, merged