Select ROI GUI refactor
didymo/OnkoDICOM pull request #216
Opened 2022-09-15 02:16 UTC by pedrooste

In order to place the draw ROI window inside of the main Onko window, we must first move the step that allows the user to select an ROI.

This will instead be placed under a button on the draw ROI window, which will then trigger the original select ROI popup.

Logging has been introduced for newly added/modified methods.

No testing is present on this branch as no changes have been fundamentally made to the select ROI functionality. One thing that could be tested is the saving restriction, where the user must select an ROI type before saving. However, this is trivial within QT due to the use of popup messages/screens.

2022-09-15 06:34 UTC, nwilde approved these changes
Looks good, gave it a quick test seems to work well 👍

2022-09-15 07:32 UTC, didymo requested changes
Logging should be debug not info.

2022-09-16 00:46 UTC, nwilde approved these changes

2022-09-16 02:25 UTC, pedrooste commented
Made another small change regarding the button text on the select ROI popup :)

2022-09-16 02:33 UTC, nwilde approved these changes

2022-09-19 00:32 UTC, SeanOverton approved these changes
Nice one 👍

2022-09-19 02:17 UTC, as565 approved these changes

2022-09-19 23:59 UTC, merged