Kaplan meier
didymo/OnkoDICOM pull request #229
Opened 2022-10-07 05:24 UTC by Santi2468

Created Keplan Meier Plot tab within batch processing to generate plot from user selected columns

2022-10-08 03:25 UTC, pedrooste commented on requirements.txt
> +matplotlib
matplotlib is already in this file, has Ashley confirmed on kaplanmeir

2022-10-08 03:27 UTC, pedrooste commented on src/Controller/BatchProcessingController.py
> +        self.kaplanmeier_AliveOrDeadCol = AliveOrDead
pretty sure this against python convention as we can directly access?

2022-10-08 03:30 UTC, pedrooste commented on src/Model/batchprocessing/BatchProcessKaplanMeier.py
> +        "1.2.840.10008.5.1.4.1.1.88.33": {
theres a generic file for these ID's would be good to chuck it in there. I cant remember where it is but shouldn't be hard to find

2022-10-08 03:31 UTC, pedrooste commented on src/Model/batchprocessing/BatchProcessKaplanMeier.py
> +            return False
extract this out into a separate method "check_interrupt" or similar. call as need

2022-10-08 03:31 UTC, pedrooste commented on src/Model/batchprocessing/BatchProcessKaplanMeier.py
> +            if datasets[ds].SOPClassUID == '1.2.840.10008.5.1.4.1.1.88.33':
find the file (refer above comment)

2022-10-08 03:32 UTC, pedrooste commented on src/Model/batchprocessing/BatchProcessKaplanMeier.py
> +            logging.debug("Creating/Displaying plot")
Not much need for the dual logs

2022-10-08 03:34 UTC, pedrooste commented on src/Controller/BatchProcessingController.py
> +        self.kaplanmeier_AliveOrDeadCol = AliveOrDead
ah, actually I see that this file uses setters throughout. It would be better then to follow what was previously done as you have :)

2022-10-08 03:37 UTC, pedrooste commented on src/View/batchprocessing/KaplanMeierOptions.py
> +        self.comboboxAliveOrDead.setStyleSheet(self.stylesheet)
You seem to switch between camel and snake case naming conventions. Any reason? Otherwise pick one (snake pref)

2022-10-08 03:40 UTC, pedrooste commented on src/Model/batchprocessing/BatchProcessKaplanMeier.py
> +mp1.use("TkAgg")
Tkinter isnt included as a dependency? This would cause the PR not to build if it isn't installed

2022-10-08 03:43 UTC, pedrooste commented on src/View/batchprocessing/KaplanMeierOptions.py
> +            "Alive or Dead Column")
Most other labels are run through a _translate function. Have a look into it on the other pages as I think it's needed for accessibility.

2022-10-08 03:44 UTC, pedrooste requested changes
see comments

2022-10-08 08:23 UTC, nwilde reviewed
Overall looks good apart from a few tweaks. 
Other question is why has the `0.35` file and the vtk wheel been added to the commit? I assume it was just an accident, probably just need to remove them

2022-10-08 08:23 UTC, nwilde commented on src/Model/batchprocessing/BatchProcessKaplanMeier.py
> +        data_list = data.split("\n")
Don't know what the input data looks like but maybe consider using `splitlines()` in case you get data with `\r\n`

2022-10-08 08:23 UTC, nwilde commented on src/Model/batchprocessing/BatchProcessKaplanMeier.py
> +        for row in range(len(data_list)):
This should probably just be iteration over the `data_list` instead of using range. `for row in data_list:` or something similar

2022-10-09 01:31 UTC, didymo requested changes
deleted

2022-10-22 06:54 UTC, merged